# Generated by Django 5.2.7 on 2026-01-13 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('reminder_type', models.CharField(choices=[('water', 'Uống nước'), ('exercise', 'Tập luyện'), ('rest', 'Nghỉ ngơi'), ('meal', 'Bữa ăn'), ('medicine', 'Uống thuốc')], max_length=20)),
                ('time', models.TimeField(help_text='Giờ nhắc nhở')),
                ('days_of_week', models.JSONField(default=list, help_text='Các ngày trong tuần [0-6]')),
                ('is_enabled', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
