# Generated by Django 5.2.7 on 2026-01-13 15:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('great', '😄 Tuyệt vời'), ('good', '🙂 Tốt'), ('normal', '😐 Bình thường'), ('tired', '😓 Mệt mỏi'), ('bad', '😢 Không tốt')], default='normal', max_length=20)),
                ('workout_completed', models.BooleanField(default=False)),
                ('workout_notes', models.TextField(blank=True, help_text='Cảm nhận sau buổi tập', null=True)),
                ('energy_level', models.IntegerField(default=5, help_text='Mức năng lượng 1-10')),
                ('sleep_hours', models.FloatField(blank=True, help_text='Số giờ ngủ', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
